### ISSUE TITLE
Serious starter issue, segmentation violation, trap error 760 

### ISSUE THREAD

**Issue by SonSiont** [OpenRadioss/OpenRadioss#1043]
**Describe the bug**
The starter abort with the latest git versions with error 760 running "2010 TOYOTA YARIS (CCSA V2j)"

**To Reproduce**
git checkout c8bef46978985ea29f807901a6d4028d92d9b13d
run starter

**Expected behavior**
No failure.

**Output**
```
 +=============================================================+
 |     ABNORMAL END                                            |
 |          Segmentation Violation                             |
 |     TRACE BACK :                                            |
 +=============================================================+
   RESTART FILE(S) WRITING
 +=============================================================+

ERROR ID :    760
** ERROR TRAPPED


 RADIOSS STOP DUE TO INPUT ERROR


------------------------------------------------------------------------------------------------------------------------
|            ERROR(S) SUMMARY                               |             WARNING(S) SUMMARY                           |
------------------------------------------------------------------------------------------------------------------------
|                                                           |                                                          |
|  --- RESTART FILE(S) WRITING                1   ERROR(S)  |  --- INTERNAL                               2 WARNING(S) |
|       |                                                   |       |                                                  |
|       |                                                   |       |                                                  |
|       |---     1   ERROR ID :          760                |       |---     2 WARNING ID :         1640               |
|       | ** ERROR TRAPPED                                  |       | ** WARNING IN SPRING MATERIAL SET                |
|       |                                                   |       |                                                  |
|                                                           |                                                          |

```
**Desktop (please complete the following information):**
 - Version: see below
- Hardware Intel(R) Core(TM) i7-5930K CPU @ 3.50GHz (x86_64), 3499 MHz,  64217 MB RAM
- Configuration STARTER RUNNING ON    1 THREAD

**Additional context**

Last working with 5f471d5ff40638a022a77004c194e461fd4d4e95
Not working with c8bef46978985ea29f807901a6d4028d92d9b13d
still not working with b64f5dc7b2ab71fa1188718a51cf054aa42de04b

**Comment by OlivierWienholtz** [comment]
Hello, 
I d'like to know if you run on Linux or Windows.

Best Regards,
Olivier

**Comment by SonSiont** [comment]
I run on Linux gcc-9 and gcc-12
thanks
SonSiont

**Comment by OlivierWienholtz** [comment]
Thank You for your information & raisons this issue.
I'll have a look.

**Comment by SonSiont** [comment]
I looked for the point of failure with gdb, ``DEBUG_PRINT = 1`` and  a namelist print before the assignment . I got:
```
       EOS  UVAR=           0
       TOTAL INTERLAYER=           0
       NVAR_GLOB=         116         117
       COMMON GLOB=         124
       GLOB NPG > 1 =           0
       TOTAL GLOB VARS =          24
       NPAR_TAB=           9
   **  LAYER=           1
       NPAR_LAY=          13
       NVAR_LAY=          12
       NVAR_LOC=          62
       LAYER_VARS=           0
     total layer vars =          87
       LOCAL VARS (LBUF TABLES)=        5640
       MAT UVAR=         512
       FAIL UVAR=           0
       VISC UVAR=           0
       NLOC UVAR=           0
&SSDBGRBU
 L_REL=6248       ,
 NEL=128        ,
 NUVAR=0          ,
 IR=1          ,
 IS=1          ,
 IT=1          ,
 /

Program received signal SIGSEGV, Segmentation fault.
0x0000000000dc0fe0 in w_elbuf_str (proc=0, iparg=..., elbuf_tab=..., len_am=144703216, flag_xfem=0) at /opt2/OpenRadioss/starter/source/restart/ddsplit/w_elbuf_str.F:901
901                        RBUF_L(L_REL+1:L_REL+NEL*NUVAR)=BUFLY%EOS(IR,IS,IT)%VAR(1:NEL*NUVAR)
Missing separate debuginfos, use: zypper install libcrypt1-debuginfo-4.4.15-150300.4.4.3.x86_64 libgcc_s1-gcc12-debuginfo-12.2.1+git749-lp154.49.1.x86_64 libgfortran5-gcc12-debuginfo-12.2.1+git749-lp154.49.1.x86_64 libgomp1-gcc12-debuginfo-12.2.1+git749-lp154.49.1.x86_64 libquadmath0-gcc12-debuginfo-12.2.1+git749-lp154.49.1.x86_64 libstdc++6-gcc12-debuginfo-12.2.1+git749-lp154.49.1.x86_64 libuuid1-debuginfo-2.37.2-150400.8.14.1.x86_64
(gdb) backtrace
#0  0x0000000000dc0fe0 in w_elbuf_str (proc=0, iparg=..., elbuf_tab=..., len_am=144703216, flag_xfem=0)
    at /opt2/OpenRadioss/starter/source/restart/ddsplit/w_elbuf_str.F:901
#1  0x0000000000d539dd in ddsplit (p=1, cep=..., cel=..., igeo=..., matparam_tab=..., ipm=..., icode=..., iskew=..., iskn=..., 
    insel=..., ibcslag=..., ipart=..., iparts=..., ipartq=..., ipartc=..., ipartt=..., ipartp=..., ipartr=..., ipartur=..., 
    iparttg=..., ipartx=..., npc=..., ixur=..., ixtg=..., group_param_tab=..., ixtg6=..., ixs=..., ixs10=..., ixs20=..., ixs16=..., 
    ixq=..., ixc=..., ixt=..., ixp=..., ixr=..., itab=..., itabm1=..., gjbufi=..., nale=..., ale_connectivity=..., kxx=..., ixx=..., 
    ibcl=..., ibfv=..., las=..., laccelm=..., nnlink=..., lllink=..., iparg=..., igrav=..., lgrav=..., ibvel=..., lbvel=..., 
    iactiv=..., factiv=..., kinet=..., ipari=..., nprw=..., lprw=..., iexmad=..., npby=..., lpby=..., ixri=..., nstrf=..., 
    ljoint=..., pornod=..., monvol=..., icontact=..., lagbuf=..., ithgrp=..., ithbuf=..., fr_iad=..., x=..., d=..., v=..., vr=..., 
    dr=..., thke=..., dampr=..., damp=..., ms=..., in=..., tf=..., pm=..., skew=..., xframe=..., geo=..., eani=..., bufmat=..., 
    bufgeo=..., bufsf=..., brmpc=..., gjbufr=..., w=..., veul=..., fill=..., dfill=..., wb=..., dsav=..., asav=..., msnf=..., 
    spbuf=..., fac=..., vel=..., fsav=..., fzero=..., xlas=..., accelm=..., fbvel=..., gravfac=..., fr_wave=..., failwave=..., 
    parts0=..., userw=..., elbuf=..., rwl=..., rwsav=..., rby=..., rivet=..., secbuf=..., rvolu=..., rconx=..., nloc_dmg=..., 
    fvmain=..., libagale=<optimized out>, lenthg=<optimized out>, lbufmat=<optimized out>, lbufgeo=<optimized out>, 
    lbufsf=<optimized out>, lenxlas=<optimized out>, lnom_opt=<optimized out>, lenlas=<optimized out>, lenvolu=<optimized out>, 
    npts=<optimized out>, cne=..., lcne=<optimized out>, addcne=..., cni2=..., lcni2g=<optimized out>, addcni2=..., cepi2=..., 
    celi2=..., i2nsnt=<optimized out>, probint=<optimized out>, ddstat=..., pm1shf=<optimized out>, dd_iad=..., lshsub=..., 
    drsav=..., arsav=..., stsav=..., strsav=..., fsavsav=..., kxsp=..., ixsp=..., nod2sp=..., cepsp=..., nthwa=<optimized out>, 
    nairwa=<optimized out>, nmnt=<optimized out>, l_mul_lag1=<optimized out>, l_mul_lag=<optimized out>, lwaspio=<optimized out>, 
    ipartsp=..., ispcond=..., pm1sph=<optimized out>, wma=..., eigipm=..., eigibuf=..., eigrpm=..., iflow=..., rflow=..., 
    memflow=..., iexlnk=..., fasolfr=..., ithgrpa=..., ithgrpb=..., ithgrpc=..., ithgrpd=..., ithgrpe=..., ithgrpf=..., ithgrpg=..., 
    ithgrph=..., ithgrpi=..., ithbufa=..., ithbufb=..., ithbufc=..., ithbufd=..., ithbufe=..., ithbuff=..., ithbufg=..., ithbufh=..., 
    ithbufi=..., iparth=..., fxbipm=..., fxbrpm=..., fxbnod=..., fxbmod=..., fxbglm=..., fxbcpm=..., fxbcps=..., fxblm=..., 
    fxbfls=..., fxbdls=..., fxbdep=..., fxbvit=..., fxbacc=..., fxbelm=..., fxbsig=..., fxbgrvi=..., fxbgrvr=..., iadll=..., lll=..., 
    ibmpc=..., lambda=..., lrbagale=<optimized out>, iskwp=..., nskwp=..., isensp=..., nsensp=..., iaccp=..., naccp=..., 
    ipart_state=..., mcp=..., temp=..., unitab=..., intstamp=..., iframe=..., clusters=..., partsav=..., ibft=..., fbft=..., 
    ibcv=..., fconv=..., irbe3=..., lrbe3=..., frbe3=..., front_rm=..., rbym=..., irbym=..., lcrbym=..., inoise=..., fnoise=..., 
    ms0=..., admsms=..., nom_sect=..., ispsym=..., sh4tree=..., sh3tree=..., ipadmesh=..., ibfflux=..., fbfflux=..., sh4trim=..., 
    sh3trim=..., padmesh=..., msc=..., mstg=..., inc=..., intg=..., ptg=..., mcpc=..., mcptg=..., rcontact=..., acontact=..., 
    pcontact=..., mscnd=..., incnd=..., mssa=..., mstr=..., msp=..., msrt=..., ibcr=..., fradia=..., dmelc=..., dmeltg=..., 
    dmels=..., dmeltr=..., dmelp=..., dmelrt=..., res_sms=..., isphio=..., lprtsph=..., lonfsph=..., vsphio=..., sphveln=..., 
    alph=..., ifill=..., ims=..., irbe2=..., lrbe2=..., ms_ply=..., zi_ply=..., inod_pxfem=..., iel_pxfem=..., icodply=..., 
    iskwply=..., addcne_pxfem=..., cne_pxfem=..., cel_pxfem=..., ithvar=..., xdp=..., table=..., celsph=..., icfield=..., 
    lcfield=..., cfield=..., usernods=..., iuserw=..., suserw=<optimized out>, siuserw=<optimized out>, msz2=..., 
--Type <RET> for more, q to quit, c to continue without paging--
    itask=<optimized out>, diag_sms=..., iloadp=..., lloadp=..., loadp=..., inod_crkxfem=..., iel_crkxfem=..., addcne_crkxfem=..., 
    cne_crkxfem=..., cel_crkxfem=..., ibufssg_io=..., intercep=..., ibordnode=..., iedgesh=..., ibordedge=..., linale=..., 
    nodedge=..., iedge=..., cep_crkxfem=..., iedge_tmp=..., crknodiad=..., elbuf_tab=..., nom_opt=..., lgauge=..., gauge=..., 
    igaup=..., ngaup=..., nodlevxf=..., frontb_r2r=..., dflow=..., vflow=..., wflow=..., sph2sol=..., sol2sph=..., irst=..., 
    elcutc=..., nodenr=..., kxfenod2elc=..., enrtag=..., intbuf_tab=..., i11flag=<optimized out>, xfem_tab=..., 
    lenthgr=<optimized out>, rthbuf=..., ixig3d=..., kxig3d=..., knot=..., ipartig3d=..., wige=..., ncrkpart=<optimized out>, 
    indx_crk=..., crklvset=..., crkshell=..., crksky=..., crkavx=..., crkedge=..., fbsav6=..., tabsensor=..., sensor_tab=..., 
    stack=..., xfem_phantom=..., t8=..., tab_ump=..., poin_ump=..., sol2sph_typ=..., addcsrect=..., csrect=..., drape=..., 
    itagnd=..., icnds10=..., addcncnd=..., cepcnd=..., celcnd=..., cncnd=..., nativ_sms=..., i24maxnsne=<optimized out>, 
    multi_fvm=..., segquadfr=..., intbuf_fric_tab=..., subset=..., igrnod=..., igrbric=..., igrquad=..., igrsh4n=..., igrsh3n=..., 
    igrtruss=..., igrbeam=..., igrspring=..., igrpart=..., igrsurf=..., igrslin=..., poin_part_shell=..., poin_part_tri=..., 
    poin_part_sol=..., mid_pid_shell=..., mid_pid_tri=..., mid_pid_sol=..., tag_nm=..., nindx_nm=<optimized out>, indx_nm=..., 
    tag_scratch=..., nindx_scrt=<optimized out>, indx_scrt=..., flag_24_25=<optimized out>, numnod_l=<optimized out>, tag_skn=..., 
    multiple_skew=..., igrsurf_proc=..., knotlocpc=..., knotlocel=..., ale_elm=..., size_ale_elm=<optimized out>, pinch_data=..., 
    tag_skins6=..., ibcscyc=..., lbcscyc=..., t_monvol=..., indx_s=..., indx_q=..., indx_tg=..., face_elm_s=..., face_elm_q=..., 
    face_elm_tg=..., nbr_th_monvol=<optimized out>, ebcs_tab=..., kloadpinter=..., loadpinter=..., dgaploadint=..., 
    s_loadpinter=<optimized out>, len_cep=<optimized out>) at /opt2/OpenRadioss/starter/source/restart/ddsplit/ddsplit.F:3044
#2  0x0000000000e66af6 in lectur_._omp_fn.0 () at /opt2/OpenRadioss/starter/source/starter/lectur.F:10660
#3  0x00007ffff7f5eea6 in GOMP_parallel () from /usr/lib64/libgomp.so.1
#4  0x0000000000ecbaa1 in lectur (multi_fvm=..., lsubmodel=..., is_dyna=<optimized out>, detonators=..., ebcs_tab=..., 
    seatbelt_converted_elements=..., nb_seatbelt_shells=<optimized out>) at /opt2/OpenRadioss/starter/source/starter/lectur.F:10528
#5  0x0000000000ecf0a5 in starter0 () at /opt2/OpenRadioss/starter/source/starter/starter0.F:859
#6  0x000000000045935e in starter () at /opt2/OpenRadioss/starter/source/starter/starter.F:42
#7  main (argc=<optimized out>, argv=<optimized out>) at /opt2/OpenRadioss/starter/source/starter/starter.F:35
#8  0x00007ffff4d6229d in __libc_start_main () from /lib64/libc.so.6
#9  0x00000000004596da in _start () at ../sysdeps/x86_64/start.S:120
(gdb) 
```
best regards

**Comment by SonSiont** [comment]
Hi,
with the commit 869332113a42ef687873220d309d1a9682135758 the job run. I will check it further.
thanks

**Comment by OlivierWienholtz** [comment]
Hello, 
Thank you for testing again.
Indeed, some issue was identified, but it is 6429a110b73d0ac0ef0a393a349304860faaba1e
which belongs to EOS...
